quarkus.http.port=8081
%test.quarkus.http.test-port=0
quarkus.timefold.solver."seating".solver-config-xml=seatingSolverConfig.xml
quarkus.timefold.solver."seating".termination.spent-limit=6s
quarkus.timefold.solver."seating".termination.best-score-limit=0hard/0soft
quarkus.timefold.solver."timetable".solver-config-xml=timetableSolverConfig.xml
quarkus.timefold.solver."timetable".termination.spent-limit=120s
quarkus.timefold.solver."timetable".termination.best-score-limit=0hard/*soft
%test.quarkus.timefold.solver."seating".termination.spent-limit=2s
%test.quarkus.timefold.solver."seating".termination.best-score-limit=0hard/*soft
%test.quarkus.timefold.solver."timetable".termination.spent-limit=5s
%test.quarkus.timefold.solver."timetable".termination.best-score-limit=0hard/*soft
