quarkus.http.port=8081
quarkus.timefold.solver.termination.spent-limit=6s
quarkus.timefold.solver.termination.best-score-limit=0hard/0soft
%test.quarkus.timefold.solver.termination.spent-limit=1h
%test.quarkus.timefold.solver.termination.best-score-limit=0hard/*soft
